In [5]:
#basic Array operations
import numpy as np


# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print ('first array \n ',  a)
print ('second array \n ',  b)


# Basic operations
print("a + b =", a + b)
print("a * b =", a * b)


first array 
  [1 2 3]
second array 
  [4 5 6]
a + b = [5 7 9]
a * b = [ 4 10 18]


In [15]:
#Array Indexing and Slicing


# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


# Accessing elements
print("Element at row 2, column 2:", arr[1, 1])

# Slicing
print("First two rows:\n", arr[:2])
print("Second column:\n", arr[:, 1])

#Slicing syntax array[start:stop:step].


#slicing array with step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print('slicing with step \n',arr[1:5:1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 2, column 2: 5
First two rows:
 [[1 2 3]
 [4 5 6]]
Second column:
 [2 5 8]
slicing with step 
 [2 3 4 5]


In [ ]:
#Broadcasting and Vectorization

a = np.array([1, 2, 3])
b = np.array([1])

print("a + b =", a + b)  # Broadcasting
print("a + b =", a / b)  # Broadcasting


In [28]:
#functions & Aggregations
arr = np.random.randint(20, 30, size=(8, 8))  # 5x5 array of random integers

print("Original array:\n", arr)
print("Array mean:", np.mean(arr))
print("Sum of all elements:", np.sum(arr))
print("Maximum element:", np.max(arr))


Original array:
 [[21 29 21 26 25 26 20 23]
 [29 20 27 23 22 28 23 20]
 [27 25 27 22 20 27 29 26]
 [20 27 23 28 22 21 22 28]
 [28 29 25 21 22 27 28 25]
 [27 24 23 25 28 29 21 25]
 [24 27 26 23 24 20 26 27]
 [25 22 26 21 24 22 20 21]]
Array mean: 24.40625
Sum of all elements: 1562
Maximum element: 29


In [30]:
#boolean indexing and Masking

arr = np.array([1, 2, 3, 4, 5])

# Boolean mask
mask = arr > 2
print("Elements greater than 3:", arr[mask])


Elements greater than 3: [3 4 5]


In [34]:
#linear Algebra operations


# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A Array is \n',A)
print('B Array is \n',B)

print("Dot product:\n", np.dot(A, B))
print("Matrix multiplication:\n", A @ B)  
print("Matrix multiplication:\n", np.matmul(A,B))




A Array is 
 [[1 2]
 [3 4]]
B Array is 
 [[5 6]
 [7 8]]
Dot product:
 [[19 22]
 [43 50]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix multiplication:
 [[19 22]
 [43 50]]
